apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: tilleggsstonader-soknad
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "25M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"

spec:
  image:  {{ image }}
  replicas:
    min: 1
    max: 2
  port: 3000
  liveness:
    path: /tilleggsstonader/soknad/internal/isAlive
    initialDelay: 5
  readiness:
    path: /tilleggsstonader/soknad/internal/isReady
    initialDelay: 5
  prometheus:
    enabled: false
    path: /metrics
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /tilleggsstonader/soknad/**/*.css
      level: Level4
  tokenx:
    enabled: true
  ingresses:
    - https://www.nav.no/tilleggsstonader/soknad
  accessPolicy:
    outbound:
      rules:
        - application: tilleggsstonader-soknad-api
        - application: familie-dokument
          namespace: teamfamilie
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        - host: nav.no
  env:
    - name: APP_VERSION
      value: '{{version}}'
    - name: ENV
      value: prod
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
