export type Ytelse =
    | 'AAP'
    | 'OVERGANGSSTØNAD'
    | 'GJENLEVENDEPENSJON'
    | 'UFØRETRYGD'
    | 'TILTAKSPENGER'
    | 'DAGPENGER'
    | 'SYKEPENGER'
    | 'KVALIFISERINGSSTØNAD'
    | 'INGEN_PENGESTØTTE'
    | 'INGEN_PASSENDE_ALTERNATIVER';
