export enum AnnenAktivitetType {
    TILTAK = 'TILTAK',
    UTDANNING = 'UTDANNING',
    ARBEIDSSØKER = 'ARBEIDSSØKER',
    INGEN_AKTIVITET = 'INGEN_AKTIVITET',
}

export enum AktivitetTypeUtdanning {
    VIDEREGÅENDE = 'VIDEREGÅENDE',
    OPPLÆRING_FOR_VOKSNE = 'OPPLÆRING_FOR_VOKSNE',
    ANNET_TILTAK = 'ANNET_TILTAK',
}
