name: Bygg app og kjør Playwright-tester

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Bygger appen"
    permissions:
      contents: read
    uses: navikt/tilleggsstonader/.github/workflows/ts-build-pnpm.yml@pnpm-workflows
    secrets: inherit
    with:
      node-version: "24"
  playwright:
    name: Kjører Playwright-tester
    permissions:
      contents: read
    uses: navikt/tilleggsstonader/.github/workflows/run-playwright-pnpm.yml@pnpm-workflows
    secrets: inherit
    with:
      node-version: "24"